In [11]:
import pandas as pd

In [12]:
all_christ= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\All_chrch_file.csv")

In [13]:
all_christ.sample(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,Pub_date,Difference_date
9122,1435223539534463655,Comfy room near hills and ocean,157306656.0,Bridie,Christchurch City,Heathcote Ward,-43.557390,172.669330,Private room,NaN,1.0,0,NaN,NaN,1.0,0,0,NaN,2025-12-11,NaN
3353,1437316641058188086,Beach House Taylor’s Mistake,339966059.0,Joanne,Christchurch City,Heathcote Ward,-43.583823,172.774905,Entire home/apt,274.0,2.0,27,2025-11-08,5.36,1.0,225,27,NaN,2025-11-07,-1.0
22831,47475702,“Graylees” Stunning Private Family Home,383228488.0,Jean,Christchurch City,Halswell Ward,-43.574980,172.547890,Entire home/apt,403.0,2.0,62,2024-07-14,0.97,1.0,101,0,NaN,2026-05-23,678.0
4534,1345944538708947216,Convenient 1Bed Studio with Ensuite By Hagley ...,49642171.0,Xihang,Christchurch City,Spreydon Ward,-43.542141,172.613152,Entire home/apt,108.0,1.0,13,2025-11-03,1.46,88.0,154,13,NaN,2025-11-07,4.0
1400,1337204397842159080,Cathedral Junction Apartment,535222454.0,Mieke,Christchurch City,Central Ward,-43.530640,172.638778,Entire home/apt,206.0,2.0,46,2025-10-04,5.90,1.0,53,46,NaN,2025-11-07,34.0
15047,927059385903578638,Latimer Square 1 bed 1 bath - Single Level,482671075.0,Care Property Stays,Christchurch City,Central Ward,-43.530298,172.641421,Entire home/apt,NaN,1.0,135,2026-01-28,4.27,134.0,195,38,NaN,2026-02-13,16.0
21684,1601827855510006415,Victoria Jane Luxury Private Guest House Chch,321971573.0,Mike,Christchurch City,Harewood Ward,-43.465853,172.617078,Entire home/apt,288.0,1.0,5,2026-04-11,2.50,1.0,178,5,NaN,2026-04-16,5.0
15012,1390911116516704002,"Bright City Base - 1Bed, Kitchen, Outdoor Space",202585247.0,Ohana,Christchurch City,Central Ward,-43.526948,172.639810,Entire home/apt,NaN,1.0,57,2026-02-03,5.38,133.0,123,57,NaN,2026-02-13,10.0
1990,1504173086779310217,Private ground floor space with its own entrance,572202728.0,Angela,Christchurch City,Coastal Ward,-43.486116,172.718882,Private room,77.0,1.0,0,NaN,NaN,1.0,244,0,NaN,2025-11-07,NaN
27413,993870335455542325,Parklands Pad,425092691.0,Zach,Christchurch City,Coastal Ward,-43.475510,172.699360,Entire home/apt,137.0,1.0,46,2026-03-23,1.41,1.0,48,4,NaN,2026-06-19,88.0

In [14]:
df_all_christ= all_christ.drop(columns=["license","id",])

In [15]:
df_all_christ.sample(10)

,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,Pub_date,Difference_date
18367,it's a home surrounding with lot of amenities.,732323895.0,Dhiren,Christchurch City,Cashmere Ward,-43.564546,172.627268,Entire home/apt,240.0,1.0,2,2026-02-28,2.00,1.0,356,2,2026-03-17,17.0
10367,Inner City Comfort,2836786.0,Karen,Christchurch City,Central Ward,-43.527940,172.645690,Private room,NaN,1.0,278,2025-12-31,2.37,1.0,333,14,2026-01-16,16.0
6342,Moncks bay retreat,8558995.0,Judith,Christchurch City,Heathcote Ward,-43.567260,172.744260,Private room,NaN,2.0,36,2025-11-20,0.50,2.0,169,3,2025-12-11,21.0
14949,City Terrace-3 Bedroom in CBD Free parking,584558161.0,Tiaki BnB,Christchurch City,Central Ward,-43.526452,172.631474,Entire home/apt,NaN,1.0,23,2025-02-11,1.23,8.0,151,0,2026-02-13,367.0
9010,Deluxe Queen Room,270614463.0,Samuel William,Christchurch City,Central Ward,-43.532810,172.627220,Private room,NaN,1.0,34,2025-10-31,0.86,14.0,0,19,2025-12-11,41.0
16665,Cozy:Fully Equipped Unit 12noon check-in,153690508.0,Rahul,Christchurch City,Papanui Ward,-43.481870,172.629210,Entire home/apt,103.0,1.0,285,2026-02-28,8.62,1.0,321,40,2026-03-17,17.0
21719,"Classic Kiwi Bach - 2 Bed, 4 guests with Hot Tub.",20665858.0,Adam,Christchurch City,Banks Peninsula Ward,-43.816021,172.950900,Entire home/apt,NaN,1.0,5,2026-03-26,2.00,21.0,311,5,2026-04-16,21.0
7942,Chic in the City,176508106.0,Shar,Christchurch City,Central Ward,-43.529620,172.657330,Entire home/apt,NaN,2.0,43,2025-11-30,1.48,1.0,326,17,2025-12-11,11.0
25395,Sea Side Paradise - Beach Across,514180659.0,Lux Property Care,Christchurch City,Coastal Ward,-43.503668,172.729149,Entire home/apt,182.0,1.0,174,2026-06-05,4.63,3.0,349,27,2026-06-19,14.0
16781,"Beachside Townhouse, 2 Bedrooms 2-3 beds, 2 bath",537639282.0,Judith,Christchurch City,Coastal Ward,-43.509601,172.731309,Entire home/apt,318.0,1.0,26,2025-12-27,0.90,4.0,296,6,2026-03-17,80.0

In [17]:
df_all_christ.dtypes

name                                  str
host_id                           float64
host_name                             str
neighbourhood_group                   str
neighbourhood                         str
latitude                          float64
longitude                         float64
room_type                             str
price                             float64
minimum_nights                    float64
number_of_reviews                   int64
last_review                           str
reviews_per_month                 float64
calculated_host_listings_count    float64
availability_365                    int64
number_of_reviews_ltm               int64
Pub_date                              str
Difference_date                   float64
dtype: object

In [19]:
df_all_christ['last_review']=pd.to_datetime(df_all_christ['last_review'])
df_all_christ['Pub_date']=pd.to_datetime(df_all_christ['Pub_date'])

In [20]:
df_all_christ.dtypes

name                                         str
host_id                                  float64
host_name                                    str
neighbourhood_group                          str
neighbourhood                                str
latitude                                 float64
longitude                                float64
room_type                                    str
price                                    float64
minimum_nights                           float64
number_of_reviews                          int64
last_review                       datetime64[us]
reviews_per_month                        float64
calculated_host_listings_count           float64
availability_365                           int64
number_of_reviews_ltm                      int64
Pub_date                          datetime64[us]
Difference_date                          float64
dtype: object

In [21]:
df_all_christ["price"].isnull().sum()

np.int64(10667)

In [22]:
df_all_christ.info()

<class 'pandas.DataFrame'>
RangeIndex: 28795 entries, 0 to 28794
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   name                            28795 non-null  str
 1   host_id                         28795 non-null  float64
 2   host_name                       28794 non-null  str
 3   neighbourhood_group             28795 non-null  str
 4   neighbourhood                   28795 non-null  str
 5   latitude                        28795 non-null  float64
 6   longitude                       28795 non-null  float64
 7   room_type                       28795 non-null  str
 8   price                           18128 non-null  float64
 9   minimum_nights                  28758 non-null  float64
 10  number_of_reviews               28795 non-null  int64
 11  last_review                     26168 non-null  datetime64[us]
 12  reviews_per_month               26168 non-null  float64
 13  calculated_host_listings_count  28795 non-null  float64
 14  availability_365                28795 non-null  int64
 15  number_of_reviews_ltm           28795 non-null  int64
 16  Pub_date                        28795 non-null  datetime64[us]
 17  Difference_date                 26168 non-null  float64
dtypes: datetime64[us](2), float64(8), int64(3), str(5)
memory usage: 4.0 MB

In [23]:
df_all_christ["last_review"].isnull().sum()

np.int64(2627)