In [2]:
import pandas as pd

In [4]:
df_tnc= pd.read_csv(r"C:\Users\VISHAL\Desktop\g2\cleaned_dataset_bond.csv")

In [5]:
df_tnc.sample(10)

,TimeFrame,Location Id,Dwelling Type,Number Of Beds,Total Bonds,Active Bonds,Closed Bonds,Median Rent,Geometric Mean Rent,Upper Quartile Rent,Lower Quartile Rent,Log Std Dev Weekly Rent
17023,2026-01-01,180100.0,House,3,6,213,21,595.0,466.0,619.0,470.0,0.5268
15523,2026-01-01,177900.0,House,ALL,24,363,30,580.0,593.0,638.0,550.0,0.1717
7333,2026-04-01,171700.0,House,ALL,9,51,6,620.0,629.0,663.0,600.0,0.0885
12968,2026-01-01,150400.0,ALL,3,6,114,3,695.0,685.0,715.0,638.0,0.1045
17942,2025-10-01,171802.0,ALL,1,6,9,3,525.0,492.0,666.0,376.0,0.4108
3715,2026-04-01,307300.0,ALL,ALL,18,177,18,435.0,514.0,690.0,410.0,0.2675
12439,2026-01-01,139900.0,ALL,2,6,126,18,565.0,588.0,615.0,545.0,0.1534
21000,2025-10-01,217200.0,ALL,ALL,9,75,3,660.0,690.0,713.0,648.0,0.1029
15507,2026-01-01,176200.0,House,ALL,21,279,33,715.0,729.0,780.0,680.0,0.1193
751,2026-04-01,224200.0,ALL,1,9,18,0,630.0,672.0,740.0,610.0,0.1641

In [6]:
df_tnc.describe()

,Location Id,Total Bonds,Active Bonds,Closed Bonds,Median Rent,Geometric Mean Rent,Upper Quartile Rent,Lower Quartile Rent,Log Std Dev Weekly Rent
count,26991.000000,26991.000000,26991.000000,26991.000000,26991.000000,26991.000000,26991.000000,26991.000000,26991.000000
mean,211184.630914,15.022674,129.579638,9.724908,617.626431,603.207180,688.976140,548.876996,0.236571
std,77610.287578,18.661899,139.441010,14.016970,156.083371,155.852902,184.304944,149.564347,0.175267
min,100100.000000,6.000000,3.000000,0.000000,90.000000,96.000000,98.000000,61.000000,0.000000
25%,143200.000000,6.000000,39.000000,3.000000,535.000000,512.000000,590.000000,468.000000,0.115900
50%,194000.000000,9.000000,87.000000,6.000000,608.000000,595.000000,665.000000,550.000000,0.189200
75%,253100.000000,18.000000,171.000000,12.000000,690.000000,681.000000,758.000000,629.000000,0.308500
max,363300.000000,654.000000,1755.000000,444.000000,3350.000000,2818.000000,3575.000000,2785.000000,3.154100

In [7]:
df_tnc.info()

<class 'pandas.DataFrame'>
RangeIndex: 26991 entries, 0 to 26990
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   TimeFrame                26991 non-null  str
 1   Location Id              26991 non-null  float64
 2   Dwelling Type            26991 non-null  str
 3   Number Of Beds           26133 non-null  str
 4   Total Bonds              26991 non-null  int64
 5   Active Bonds             26991 non-null  int64
 6   Closed Bonds             26991 non-null  int64
 7   Median Rent              26991 non-null  float64
 8   Geometric Mean Rent      26991 non-null  float64
 9   Upper Quartile Rent      26991 non-null  float64
 10  Lower Quartile Rent      26991 non-null  float64
 11  Log Std Dev Weekly Rent  26991 non-null  float64
dtypes: float64(6), int64(3), str(3)
memory usage: 2.5 MB

In [8]:
df_tnc.isna().sum()

TimeFrame                    0
Location Id                  0
Dwelling Type                0
Number Of Beds             858
Total Bonds                  0
Active Bonds                 0
Closed Bonds                 0
Median Rent                  0
Geometric Mean Rent          0
Upper Quartile Rent          0
Lower Quartile Rent          0
Log Std Dev Weekly Rent      0
dtype: int64

In [8]:
df_tnc['TimeFrame']=pd.to_datetime(df_tnc['TimeFrame'])

In [9]:
#import libraries
import pandas as pd
from pathlib import Path

In [ ]:
#Load dataset
df = pd.read_csv(r"C:\Users\patel\OneDrive\Desktop\new repo\GRP_Project_422_201\Detailed-Quarterly-Tenancy-Q1-2020-Q3-2026.csv")

print(df.shape)
df.head()

(226080, 12)

,TimeFrame,Location Id,Dwelling Type,Number Of Beds,Total Bonds,Active Bonds,Closed Bonds,Median Rent,Geometric Mean Rent,Upper Quartile Rent,Lower Quartile Rent,Log Std Dev Weekly Rent
0,2026-04-01,NaN,ALL,1,2064,19563,1176,NaN,NaN,NaN,NaN,NaN
1,2026-04-01,-99.0,ALL,1,22014,113820,6969,550.0,522.0,660.0,450.0,0.4144
2,2026-04-01,100100.0,ALL,1,6,9,0,425.0,408.0,475.0,370.0,0.2834
3,2026-04-01,100600.0,ALL,1,6,12,3,588.0,585.0,720.0,545.0,0.2550
4,2026-04-01,100700.0,ALL,1,6,30,3,550.0,530.0,579.0,473.0,0.1588

In [ ]:
# Convert TimeFrame to datetime
df["TimeFrame"] = pd.to_datetime(df["TimeFrame"], errors="coerce")

# Check for invalid dates
if df["TimeFrame"].isna().any():
    raise ValueError("Invalid or missing TimeFrame values found.")

print("TimeFrame converted successfully.")

TimeFrame converted successfully.

In [ ]:
#  Filter timeframe Keep only Oct 2025 to Jun 2026
bond = df[
    (df["TimeFrame"] >= "2025-10-01") &
    (df["TimeFrame"] < "2026-07-01")
].copy()

print("Rows before:", len(df))
print("Rows after:", len(bond))
print("Rows removed:", len(df) - len(bond))

bond["TimeFrame"].value_counts().sort_index()

Rows before: 226080
Rows after: 27212
Rows removed: 198868

TimeFrame
2025-10-01    9459
2026-01-01    9255
2026-04-01    8498
Name: count, dtype: int64

In [ ]:
#check missing values in each column
print("Missing values in each column:")
bond.isna().sum()

Missing values in each column:

TimeFrame                    0
Location Id                 94
Dwelling Type                0
Number Of Beds             890
Total Bonds                  0
Active Bonds                 0
Closed Bonds                 0
Median Rent                 94
Geometric Mean Rent         94
Upper Quartile Rent         94
Lower Quartile Rent         94
Log Std Dev Weekly Rent     94
dtype: int64

In [ ]:
# Data Quality investigate
checks = pd.DataFrame({
    "TimeFrame": bond["TimeFrame"],
    "Missing Location": bond["Location Id"].isna(),
    "Missing Beds": bond["Number Of Beds"].isna(),
    "Missing Rent": bond["Median Rent"].isna(),
    "Location -99": bond["Location Id"] == -99
})

checks.groupby("TimeFrame").sum()

            Missing Location  Missing Beds  Missing Rent  Location -99
TimeFrame
2025-10-01                32           819            32            46
2026-01-01                33            41            33            41
2026-04-01                29            30            29            40

In [ ]:
# validate numerical data
bond_columns = [
    "Total Bonds",
    "Active Bonds",
    "Closed Bonds"
]

rent_columns = [
    "Median Rent",
    "Geometric Mean Rent",
    "Lower Quartile Rent",
    "Upper Quartile Rent"
]

print("Negative bond values:")
print((bond[bond_columns] < 0).sum())

print("\nNon-positive rent values:")
print((bond[rent_columns] <= 0).sum())

invalid_quartiles = (
    (bond["Lower Quartile Rent"] > bond["Median Rent"]) |
    (bond["Median Rent"] > bond["Upper Quartile Rent"])
).sum()

print("\nInvalid quartile ordering:", invalid_quartiles)

print("Duplicate rows:", bond.duplicated().sum())

Negative bond values:
Total Bonds     0
Active Bonds    0
Closed Bonds    0
dtype: int64

Non-positive rent values:
Median Rent            0
Geometric Mean Rent    0
Lower Quartile Rent    0
Upper Quartile Rent    0
dtype: int64

Invalid quartile ordering: 0
Duplicate rows: 0

In [ ]:
# clean data set 
# Remove missing Location Id
cleaned = bond.dropna(subset=["Location Id"]).copy()

# Remove special Location Id = -99
cleaned = cleaned[cleaned["Location Id"] != -99].copy()

print("Final cleaned shape:", cleaned.shape)

# Check remaining missing values
cleaned.isna().sum()

Final cleaned shape: (26991, 12)

TimeFrame                    0
Location Id                  0
Dwelling Type                0
Number Of Beds             858
Total Bonds                  0
Active Bonds                 0
Closed Bonds                 0
Median Rent                  0
Geometric Mean Rent          0
Upper Quartile Rent          0
Lower Quartile Rent          0
Log Std Dev Weekly Rent      0
dtype: int64

In [ ]:
# verify unique keys
key_columns = [
    "TimeFrame",
    "Location Id",
    "Dwelling Type",
    "Number Of Beds"
]

duplicates = cleaned.duplicated(subset=key_columns).sum()

print("Duplicate key combinations:", duplicates)

Duplicate key combinations: 0

In [ ]:
#save cleaned dataset
output = Path("data/processed/rental_bond_cleaned_2025_10_to_2026_04.csv")

output.parent.mkdir(parents=True, exist_ok=True)

cleaned.to_csv(
    output,
    index=False,
    date_format="%Y-%m-%d"
)

print("Dataset saved successfully!")
print("Location:", output)

Dataset saved successfully!
Location: data\processed\rental_bond_cleaned_2025_10_to_2026_04.csv

In [ ]:
# verify export
saved = pd.read_csv(output)

print("Saved dataset shape:", saved.shape)

assert saved.shape == cleaned.shape
assert saved.columns.tolist() == cleaned.columns.tolist()

saved.head()

Saved dataset shape: (26991, 12)

,TimeFrame,Location Id,Dwelling Type,Number Of Beds,Total Bonds,Active Bonds,Closed Bonds,Median Rent,Geometric Mean Rent,Upper Quartile Rent,Lower Quartile Rent,Log Std Dev Weekly Rent
0,2026-04-01,100100.0,ALL,1,6,9,0,425.0,408.0,475.0,370.0,0.2834
1,2026-04-01,100600.0,ALL,1,6,12,3,588.0,585.0,720.0,545.0,0.2550
2,2026-04-01,100700.0,ALL,1,6,30,3,550.0,530.0,579.0,473.0,0.1588
3,2026-04-01,100800.0,ALL,1,15,51,0,500.0,520.0,550.0,485.0,0.0970
4,2026-04-01,101100.0,ALL,1,6,36,3,570.0,536.0,621.0,490.0,0.1942